FROM node:lts-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev --legacy-peer-deps 


COPY . .
RUN  npm install --global rimraf
RUN npm run build

# USER node

CMD [ "npm", "run", "start-docker" ]


EXPOSE 8000